services:
  - type: web
    name: snapfeast_django
    env: python
    buildcommand: |
      chmod +x build.sh
      ./build.sh
    startcommand: "gunicorn snapfeast.wsgi:application"
    ports:
      - 80:80