# Generated by Django 5.1 on 2024-09-02 02:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('Amala with Goat Meat', 'Amala with Goat Meat'), ('Jollof and Fried Rice with Chicken', 'Jollof and Fried Rice with Chicken'), ('Porridge with Vegetable', 'Porridge with Vegetable'), ('Pounded Yam with Egusi Soup', 'Pounded Yam with Egusi Soup'), ('White Rice, Beans and Fried Stew', 'White Rice, Beans and Fried Stew'), ('Yam and Fried Eggs', 'Yam and Fried Eggs'), ('Spaghetti Bolognese with Sauce', 'Spaghetti Bolognese with Sauce'), ('Chicken and Chips', 'Chicken and Chips'), ('Fruit Salad', 'Fruit Salad')], max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.meal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
