# Generated by Django 5.0.3 on 2024-06-28 21:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealorder",
            name="user_id",
        ),
        migrations.AddField(
            model_name="mealorder",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mealorder",
            name="food_type",
            field=models.CharField(
                choices=[("AMALA", "Amala"), ("PIZZA", "Pizza"), ("BURGER", "Burger")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mealorder",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
