# Generated by Django 5.0.3 on 2024-06-29 13:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_mealorder_user_id_mealorder_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("AMALA", "Amala"),
                            ("PIZZA", "Pizza"),
                            ("BURGER", "Burger"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="mealorder",
            name="food_type",
        ),
        migrations.AddField(
            model_name="mealorder",
            name="quantity",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="meal",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="orders.meal"
            ),
        ),
    ]
