# Generated by Django 5.0.3 on 2024-07-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_meal_remove_mealorder_food_type_mealorder_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="meal",
            field=models.CharField(
                choices=[
                    ("Amala with Goat Meat", "Amala with Goat Meat"),
                    (
                        "Jollof and Fried Rice with Chicken",
                        "Jollof and Fried Rice with Chicken",
                    ),
                    ("Porridge with Vegetable", "Porridge with Vegetable"),
                    ("Pounded Yam with Egusi Soup", "Pounded Yam with Egusi Soup"),
                    (
                        "White Rice, Beans and Fried Stew",
                        "White Rice, Beans and Fried Stew",
                    ),
                    ("Yam and Fried Eggs", "Yam and Fried Eggs"),
                    (
                        "Spaghetti Bolognese with Sauce",
                        "Spaghetti Bolognese with Sauce",
                    ),
                    ("Chicken and Chips", "Chicken and Chips"),
                    ("Fruit Salad", "Fruit Salad"),
                ],
                max_length=500,
                null=True,
            ),
        ),
    ]
